server:
  port: 8082
  servlet:
    context-path: /pocmicroservice
spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: order-service
  datasource:
    hikari:
      connection-timeout: 2000
    url: jdbc:postgresql://localhost:5432/pocorderdb?currentSchema=pocorder
    username: wattanai
    password: P@$$w0rd
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka #Because of adding auth in discovery server, we need to add username and password information (http://username:password@...) into url