eureka:
  username: ${EUREKA_USERNAME:eureka} #if there are no ENV Variables, then the default credentials ("eureke") will be picked up
  password: ${EUREKA_PASSWORD:password} #if there are no ENV Variables, then the default credentials ("password") will be picked up
  instance:
    hostname: localhost
  client: # Don't want to register discovery server as a client
    register-with-eureka: false
    fetch-registry: false
#  server:
#      renewal-threshold-update-interval-ms: 10000 #update status every 10 sec
server:
  port: 8761
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0